Refactoring
karapnaran/bot-hrach pull request #5
Opened 2023-05-20 23:10 UTC by tikohov20

2023-05-20 23:14 UTC, HrachAsatryan requested changes
Rewrite in Python

2023-05-21 00:15 UTC, vardgesmusakhanyan commented on VoiceCommands/connection.js
> +module.exports = connection;
We could write this section in Python

2023-05-21 00:22 UTC, tikohov20 reviewed
add masterpiece.mp3 as a fallback song

2023-05-21 00:22 UTC, tikohov20 commented on VoiceCommands/queue.js
> +      console.log(queue[0]);
remove console log

2023-05-21 00:25 UTC, HrachAsatryan commented
Please add check, if video URL is https://youtu.be/TUVcZfQe-Kw replace with https://youtu.be/WHuBW3qKm9g

2023-05-21 12:55 UTC, tikohov20 commented
> Rewrite in Python

![image](https://github.com/karapnaran/bot-hrach/assets/62335544/7cb65d91-2a8a-432d-b68e-1758a1373091)

2023-05-21 13:04 UTC, merged